#pragma once

#include "structs/BinaryPacketHeader.hpp"
#include "structs/Message.hpp"
#include "structs/MessageHeader.hpp"
#include "structs/GroupSize.hpp"
#include "structs/MaturityMonthYear.hpp"
#include "structs/GroupSize8Byte.hpp"

#include "messages/ChannelReset.hpp"
#include "messages/AdminLogin.hpp"
#include "messages/AdminLogout.hpp"
#include "messages/MdInstrumentDefinitionFuture.hpp"
#include "messages/MdInstrumentDefinitionSpread.hpp"
#include "messages/SecurityStatus.hpp"
#include "messages/MdIncrementalRefreshBook.hpp"
#include "messages/MdIncrementalRefreshDailyStatistics.hpp"
#include "messages/MdIncrementalRefreshLimitsBanding.hpp"
#include "messages/MdIncrementalRefreshSessionStatistics.hpp"
#include "messages/MdIncrementalRefreshTrade.hpp"
#include "messages/MdIncrementalRefreshVolume.hpp"
#include "messages/SnapshotFullRefresh.hpp"
#include "messages/QuoteRequest.hpp"
#include "messages/MdInstrumentDefinitionOption.hpp"
#include "messages/MdIncrementalRefreshTradeSummary.hpp"
#include "messages/MdIncrementalRefreshOrderBook.hpp"
#include "messages/SnapshotFullRefreshOrderBook.hpp"
